# Generated by Django 5.2.5 on 2026-04-20 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Titre de la session"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(max_length=50, verbose_name="Type de session"),
                ),
                ("year", models.CharField(max_length=50, verbose_name="Année")),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Spécialité"
                    ),
                ),
                (
                    "section",
                    models.IntegerField(blank=True, null=True, verbose_name="Section"),
                ),
                (
                    "assigned_groups",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Groupes assignés"
                    ),
                ),
                ("day", models.CharField(max_length=20, verbose_name="Jour")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                ("room", models.CharField(max_length=100, verbose_name="Salle")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
        migrations.CreateModel(
            name="SessionInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "teacher_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Note de l enseignant"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="schedules.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance de Session",
                "verbose_name_plural": "Instances de Session",
                "unique_together": {("session", "date")},
            },
        ),
        migrations.CreateModel(
            name="AbsenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "absence_count",
                    models.IntegerField(default=0, verbose_name="Nombre d absences"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_counters",
                        to="schedules.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compteur d absences",
                "verbose_name_plural": "Compteurs d absences",
                "unique_together": {("student", "session")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("unmarked", "Non marqué"),
                        ],
                        default="unmarked",
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="schedules.sessioninstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "unique_together": {("session_instance", "student")},
            },
        ),
    ]
