# Generated by Django 4.2 on 2026-05-02 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification_type', models.CharField(choices=[('MEDICAL', 'Médical'), ('TRANSPORT', 'Transport'), ('FAMILY', 'Famille'), ('OTHER', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to='justifications/')),
                ('status', models.CharField(choices=[('EN ATTENTE', 'En attente'), ('JUSTIFIÉE', 'Justifiée'), ('INJUSTIFIÉE', 'Injustifiée')], default='EN ATTENTE', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('scholarite_comment', models.TextField(blank=True, null=True)),
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='schedules.attendancerecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justificatif',
                'verbose_name_plural': 'Justificatifs',
            },
        ),
    ]
