# Generated by Django 4.2 on 2026-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='student_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
