# Generated by Django 4.2 on 2026-06-03 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0003_justification_student_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255, verbose_name='Module')),
                ('exam_type', models.CharField(choices=[('TD', 'TD'), ('TD_COLLECTIF', 'TD Collectif'), ('EXAM', 'Examen'), ('PARTIEL', 'Partiel')], default='TD', max_length=20)),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('year', models.CharField(max_length=10, verbose_name='Promotion')),
                ('speciality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'TEACHER'}, related_name='exam_supervisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('AMPHI', 'Amphithéâtre'), ('SALLE', 'Salle')], max_length=10)),
                ('room_name', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schedules.exam')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='exam_room_supervisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Salle d'examen",
                'verbose_name_plural': "Salles d'examen",
                'ordering': ['room_type', 'room_name'],
            },
        ),
        migrations.CreateModel(
            name='ExamStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='schedules.exam')),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='schedules.examroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_room_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation étudiant',
                'ordering': ['order'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('unmarked', 'Non marqué')], default='unmarked', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schedules.exam')),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schedules.examroom')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_exam_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence examen',
                'verbose_name_plural': 'Présences examen',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
