# Generated by Django 4.2 on 2026-06-03 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_exam_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='exam_attendance_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='schedules.examattendancerecord'),
        ),
        migrations.AlterField(
            model_name='justification',
            name='attendance_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justification', to='schedules.attendancerecord'),
        ),
    ]
