# Generated by Django 4.2 on 2026-06-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_justification_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_replacement',
            field=models.BooleanField(default=False, verbose_name='Examen de remplacement'),
        ),
        migrations.AddField(
            model_name='exam',
            name='original_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_exams', to='schedules.exam', verbose_name='Examen original'),
        ),
    ]
