# Generated by Django 5.2.5 on 2026-04-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="group",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Groupe"
            ),
        ),
    ]
