# Generated by Django 5.2.5 on 2026-04-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, verbose_name="Poste"),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                default="fr", max_length=10, verbose_name="Langue préférée"
            ),
        ),
    ]
