# Generated by Django 5.2.5 on 2026-04-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_job_title_user_preferred_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_language",
        ),
    ]
